# Generated by Django 5.2.5 on 2025-08-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
